### PR TITLE
layoutbox: Use a textbox as the fallback when no images are found

### LINKED ISSUE #896: layoutbox: fallback to textbox in case the image cannot be loaded
If the layoutbox' imagebox fails to load the image(s) (because the path in `theme.layout_*` is wrong), you end up with a layoutbox of 0x0 px.

I think that there should be a placeholder / indicator in this case - maybe falling back to displaying some text?! (e.g. by replacing the imagebox with a textbox)

What do you think?

### PR DESCRIPTION
**Pull request by Elv13**
Fix #896

### CODE REVIEW

File: lib/awful/widget/layoutbox.lua [hunk 1]
```diff
@@ -25,7 +26,12 @@ local function update(w, screen)
     screen = get_screen(screen)
     local name = layout.getname(layout.get(screen))
     w._layoutbox_tooltip:set_text(name or "[no name]")
-    w:set_image(name and beautiful["layout_" .. name])
+
+    local exists = name and beautiful["layout_" .. name]
+        and fs.file_readable(beautiful["layout_" .. name])
+
+    w.imagebox:set_image(exists and beautiful["layout_" .. name] or nil)
+    w.textbox:set_text(exists and  "" or name)
```
Comment (psychon) [inline lib/awful/widget/layoutbox.lua]: This version is fine with me, but how about the following instead (could catch more problems, but is untested):
```lua
local img = gears.surface.load_silently(beautiful["layout_" .. name], false)
if img then
    w.imagebox.image = img
    w.textbox.text = ""
else
    w.imagebox.image = nil
    w.textbox.text = name
end
```

**Comment by Elv13** [comment]
Done
