### PR TITLE
Fix 2419

### LINKED ISSUE #2419: "request::titlebars" isn't sent when used with `toggle`
Output of `awesome --version`:

4.2

**How to reproduce the issue:**
`titlebar_enabled =  true` -> `titlebar_enabled =  false` then add a keybinding to toggle them.

**Actual result:**

Nothing because `request::titlebars` wasn't called.

**Expected result:**

Somehow call the signal the first time a show/hide/toggle function is used.

(reporting it instead of a patch because I don't have time right now, its trivial to fix)

### PR DESCRIPTION
**Pull request by Elv13**
Fix #2419 #1588

### CODE REVIEW

File: lib/awful/titlebar.lua [hunk 1]
```diff
@@ -453,6 +453,32 @@ local function get_titlebar_function(c, position)
...
+    if c._request_titlebars_called then return false end
+
+    c:emit_signal("request::titlebars", "awful.titlebar", {})
+
+    if hide_all then
+        -- Don't bother checking if it has been created, `.hide` don't works
+        -- anyway.
+        for _, tb in ipairs {"top", "bottom", "left", "right"} do
+            if tb ~= keep then
+                titlebar.hide(c, tb)
```
Comment (psychon) [inline lib/awful/titlebar.lua]: This is a behaviour change.  If I do `awful.titlebar.show(c, "top")` and then `awful.titlebar.show(c, "bottom")`, the top titlebar is now hidden. Why?!?

File: lib/awful/titlebar.lua [hunk 2]
```diff
@@ -551,6 +578,7 @@ end
 --   "right", "top", "bottom". Default is "top".
 function titlebar.toggle(c, position)
     position = position or "top"
+    if load_titlebars(c, true, position) then return end
```
Comment (psychon) [inline lib/awful/titlebar.lua]: Why this new early return? This should break any keybindings that toggle titlebar visibility. I can also come up with an example where the new early return in `titlebar.show` breaks stuff.

File: lib/awful/titlebar.lua [hunk 3]
```diff
@@ -453,6 +453,32 @@ local function get_titlebar_function(c, position)
     end
 end
 
+--- Call `request::titlebars` to allow themes or rc.lua to create them even
+-- when `titlebars_enabled` is not set in the rules.
+-- @tparam client c The client.
+-- @tparam[opt=false] boolean hide_all Hide all titlebars except `keep`
+-- @tparam string keep Keep the titlebar at this position
+-- @treturn boolean If the titlebars were loaded
+local function load_titlebars(c, hide_all, keep)
```
Comment (psychon) [inline lib/awful/titlebar.lua]: This function is only ever called with `hide_all=true`. Why is this a parameter?

File: lib/awful/titlebar.lua (hunk 1 above)
Comment (Elv13) [reply lib/awful/titlebar.lua]: It wont because this code is only executed once

        if c._request_titlebars_called then return false end

File: lib/awful/titlebar.lua (hunk 2 above)
Comment (Elv13) [reply lib/awful/titlebar.lua]: Because if `load_titlebar` returns true, then it is already shown

Comment (psychon) [reply lib/awful/titlebar.lua]: Okay, and who hides it then?

File: lib/awful/titlebar.lua (hunk 1 above)
Comment (psychon) [reply lib/awful/titlebar.lua]: Oh, right. Then... why does this hide titlebars that cannot be there?

File: lib/awful/titlebar.lua (hunk 2 above)
Comment (Elv13) [reply lib/awful/titlebar.lua]: toggle?

If load_titlebar load something, then toggle will hide it. But if the user call toggle and there is no titlebar, then he/she want to show it?

Otherwise I don't understand the question

File: lib/awful/titlebar.lua (hunk 1 above)
Comment (Elv13) [reply lib/awful/titlebar.lua]: because if toggle or show is called, then the user wants to show one of them. If many are loaded, then they should not be shown.

File: lib/awful/titlebar.lua (hunk 2 above)
Comment (psychon) [reply lib/awful/titlebar.lua]: Okay, so: .... oh wait, I got the return value of `load_titlebars` wrong. Sorry!

File: lib/awful/titlebar.lua (hunk 1 above)
Comment (psychon) [reply lib/awful/titlebar.lua]: So, this is an intentional change in behaviour then and needs deprecation and has to wait until v5?
Previously, toggling the left titlebar, did not do anything with the other titlebars at all.

**Comment by psychon** [comment]
Gentle ping on "what's wrong with this patch instead?"
```diff
diff --git a/lib/awful/rules.lua b/lib/awful/rules.lua
index c652ede31..6a2ef9b76 100644
--- a/lib/awful/rules.lua
+++ b/lib/awful/rules.lua
@@ -583,6 +583,7 @@ end
 function rules.execute(c, props, callbacks)
     -- This has to be done first, as it will impact geometry related props.
     if props.titlebars_enabled then
+        c._requested_titlebars = true
         c:emit_signal("request::titlebars", "rules", {properties=props})
     end
 
diff --git a/lib/awful/titlebar.lua b/lib/awful/titlebar.lua
index 969b4076b..2df8f496c 100644
--- a/lib/awful/titlebar.lua
+++ b/lib/awful/titlebar.lua
@@ -468,6 +468,11 @@ end
 -- @tparam[opt=top] string args.font
 -- @function awful.titlebar
 local function new(c, args)
+    if not c._requested_titlebars then
+        c._requested_titlebars = true
+        c:emit_signal("request::titlebars", "awful.titlebar", {})
+    end
+
     args = args or {}
     local position = args.position or "top"
     local size = args.size or gmath.round(beautiful.get_font_height(args.font) * 1.5)
```

File: lib/awful/titlebar.lua (hunk 1 above)
Comment (Elv13) [reply lib/awful/titlebar.lua]: As far as I see, no, it does not change anything other than fixing the bug. You go from having zero titlebars. Then you want to show one of them. One of them is shown.

Because request::titlebars can potentially load 4 titlebars, the other have to be hidden since they were not requested to be shown.

**Comment by Elv13** [comment]
> Gentle ping on "what's wrong with this patch instead?"

If more than 1 titlebar is loaded by request::titlebars, it will not behave as documented.

**Comment by psychon** [comment]
Hm. So, basically, everything we can do is weird because there is an imbalance between "show this one titlebar" and "set up all the titlebars". :-/

How about fixing this in the default config instead?
Every client gets a titlebar set up and `request::titlebar` then only triggers visibility of that titlebar?

I don't really know...

**Comment by Elv13** [comment]
> How about fixing this in the default config instead?
> Every client gets a titlebar set up and request::titlebar then only triggers visibility of that titlebar?

I am neutral against adding or not adding 4 more signals. This should be done in another pull request as it doesn't fix the issue this pull request addresses. Also, given it require the user to also modify the titlebar declaration, you now have to specify the position **twice** (one in the signal name and the other in the `awful.titlebar(c {position=...})`. So it adds complexity for solving a problem less than <0.5% of the users will ever hit. Assuming that >99.5% of people has either zero or one titlebar, it's an imperfect solution. See 3rd section of this comment for my proposed long term alternative.

My solution final result is AFAIK correct for 100% of the users without any modified `rc.lua` code and behavior change. This proposed solution only solves half of the issue even if all users config could magically be upgraded, which it can't.

> Hm. So, basically, everything we can do is weird

Yes, this is why the code was written that way instead of any other way. It wasn't pretty when I wrote it and it fixes an equally ugly "race condition" bug. Right now (and since forever, given the titlebars created in "manage" in v3.5 had the same issue), we have two broken functions in `awful.titlebar`. After this patch, they are working as expected with only a potential flickering for <0.5% of the userbase who have multiple titlebars *and* use this function to toggle them.

> because there is an imbalance between "show this one titlebar" and "set up all the titlebars". :-/

Not exactly, the issue as I see it is that the concept of a titlebar area(s) and the titlebar widget are coupled beyond common sense. My proposed solution to this impasse has long been in the form of #655. It isn't done yet and I think we both agree I have too many long-ongoing pull request series to add even more. This pull request make `show` and `toggle` work when `titlebars_enabled` is set to `false` and add regression tests. It does not attempt to solve the reason why this bug exist.

File: lib/awful/titlebar.lua (hunk 3 above)
Comment (Elv13) [reply lib/awful/titlebar.lua]: A second PR will add `hide_all`/`show_all`/`toggle_all`. I didn't want to scope creep this PR.

**Comment by Elv13** [comment]
@psychon thanks

@jd I think mergify should have worked here, any idea?

**Comment by jd** [comment]
@Elv13 looks like a caching issue. I just refreshed.

**Comment by Elv13** [comment]
thanks

**Comment by blueyed** [comment]
@Elv13 
I think this change caused an issue with my config, which was not adjusted for `request::titlebars`, but created the titlebars still manually (and hides them for most clients) in manage:
```lua
        awful.titlebar(c):set_widget(layout)

        if c.type ~= 'dialog' and c.name ~= 'Thunderbird Preferences' then
          awful.titlebar.hide(c)  -- NOTE: triggers layout arranging
        end
```
The first call to `toggle` would then do nothing (also when not hiding them).
I will adjust my config to move this into a request handler also, but just wanted to note this.

File: tests/test-titlebar.lua [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+    window.application = self
+    window:show_all()
+end
+app:run {''}
+]]}
+
+-- Use the test client props
+rules.rules = {}
+
+-- Too bad there's no way to disconnect the rc.lua request::titlebars function
```
Comment (blueyed) [inline tests/test-titlebar.lua]: This could be either disconnected if it was set as a function (so its reference could be used), or with something that would allow to unset any signal handlers (for a given signal).
For the 2nd idea, it could provide a mechanism to restore them later, useful for tests and maybe even in general, if you want to execute something without any signals?!
