### PR TITLE
Remove unused first parameter in some constructors

### LINKED ISSUE #3214: Constructor for wibox.widget.slider creates white box instead of slider
Output of `awesome --version`:

```
awesome v4.3-895-g538586c17-dirty (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

Use the following rc.lua:

```lua
local wibox = require('wibox')
local shape = require('gears.shape')

local screen = screen.primary

-- Slider example from docs, but with constructor
local slider1 = wibox.widget.slider({
    bar_shape           = shape.rounded_rect,
    bar_height          = 3,
    bar_color           = "#0000ff",
    handle_color        = "#ff0000",
    handle_shape        = shape.circle,
    handle_border_color = "#0000ff",
    handle_border_width = 1,
    value               = 25,
    widget              = wibox.widget.slider,
})

-- Slider example from docs
local slider2 = wibox.widget {
    bar_shape           = shape.rounded_rect,
    bar_height          = 3,
    bar_color           = "#0000ff",
    handle_color        = "#ff0000",
    handle_shape        = shape.circle,
    handle_border_color = "#0000ff",
    handle_border_width = 1,
    value               = 25,
    widget              = wibox.widget.slider,
}

wibox({
    visible = true,
    x = screen.geometry.width / 2 - 150,
    y = screen.geometry.height * (1/3) - 50,
    width = 300,
    height = 100,
    fg = "#ffffff",
    bg = "#000000",
    widget = {
        wibox.widget.textbox("Imperative"),
        slider1,
        spacing = 5,
        widget = wibox.layout.fixed.vertical,
    },
})

wibox({
    visible = true,
    x = screen.geometry.width / 2 - 150,
    y = screen.geometry.height * (2/3) - 50,
    width = 300,
    height = 100,
    fg = "#ffffff",
    bg = "#000000",
    widget = {
        wibox.widget.textbox("Declarative"),
        slider2,
        spacing = 5,
        widget = wibox.layout.fixed.vertical,
    },
})
```

**Actual result:**

Upper wibox displays a large white box.

image

**Expected result:**

Both wiboxes should display a slider widget.

### PR DESCRIPTION
**Pull request by sclu1034**
Fixes #3214.

Likely a breaking change, even if only a few people were to use these constructors directly.

### CODE REVIEW

File: spec/wibox/widget/slider_spec.lua [hunk 1]
```diff
@@ -12,6 +12,14 @@ describe("wibox.widget.slider", function()
         widget = slider()
     end)
 
+    describe("constructor", function()
+        it("applies arguments", function()
+            local widget = slider({ value = 10 })
```
Comment (Aire-One) [inline spec/wibox/widget/slider_spec.lua:17]:
```suggestion
            widget = slider({ value = 10 })
```

This will prevent the `make check-qa`:

 ```
Checking spec/wibox/widget/slider_spec.lua        1 warning
spec/wibox/widget/slider_spec.lua:17:19: shadowing upvalue 'widget' on line 9
```

Comment (Aire-One) [inline spec/wibox/widget/slider_spec.lua:17]:
```suggestion
            widget = slider({ value = 10 })
```

This will prevent the `make check-qa` warning:

```
Checking spec/wibox/widget/slider_spec.lua        1 warning
spec/wibox/widget/slider_spec.lua:17:19: shadowing upvalue 'widget' on line 9
```

**Review by Aire-One — CHANGES_REQUESTED** [review]
Thank you for this fix!

**Review by Aire-One — APPROVED** [review]

**Comment by psychon** [comment]
Basically :+1: but since Travis is currently broken I am not actually approving this via the GH UI. (I'd like to see a successful CI run first.)

**Comment by Elv13** [comment]
Ouch, nice catch. That was broken for a loooonnnggg time!

I fixed the CI, so if you force push a random update, it should run.

Longer term, we should move those widgets to the `args` syntax most widgets now use, but first things first, lets fix this.

**Review by Aire-One — APPROVED** [review]
~I think you should squash the last commit to make the last Travis job (check every commit one-by-one) succeed.~

Or maybe we don't care, because this last commit already fix the Travis build, and we don't need to waste credits for that...

**Review by Elv13 — APPROVED** [review]

**Review by psychon — APPROVED** [review]
