### PR TITLE
fix(awful: layouts: tile: mouse_resize_handler): count the size of useless_gaps around the client (fixes #424)

### LINKED ISSUE #424: Mouse resize in tile layout works weird for the bottom row when `size_hints_honor = false`
Steps to reproduce:
1) set `size_hints_honor = false` in the rules
2) switch to tile layout
3) open 3 or more clients
4) try to resize client on the most bottom row (either slave or master if there is two or more master clients, ie more than one row)

Client size will jump crazily, while on other rows resize happens as expected.

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

File: lib/awful/layout/suit/tile.lua [hunk 1]
```diff
@@ -49,7 +49,9 @@ tile.resize_jump_to_corner = true
 local function mouse_resize_handler(c, _, _, _, orientation)
     orientation = orientation or "tile"
     local wa = c.screen.workarea
-    local mwfact = c.screen.selected_tag.master_width_factor
+    local t = c.screen.selected_tag
+    local useless_gap = t.gap
+    local mwfact = t.master_width_factor
```
Comment (Aire-One) [inline lib/awful/layout/suit/tile.lua:54]: I'm not sure whether this is correct. What happens when the user selects multiple tags?

As a possible fix, we could add a `params` parameter like the one for `arrange()`.

File: lib/awful/layout/suit/tile.lua [hunk 2]
```diff
@@ -155,7 +157,7 @@ local function mouse_resize_handler(c, _, _, _, orientation)
                                       return true
                                   end
                               end
-                              return prev_coords.x == coords.x and prev_coords.y == coords.y
+                              return (prev_coords.x == coords.x) and (prev_coords.y == coords.y)
```
Comment (Aire-One) [inline lib/awful/layout/suit/tile.lua:160]: 👍

File: lib/awful/layout/suit/tile.lua (hunk 1 above)
Comment (actionless) [reply lib/awful/layout/suit/tile.lua:54]: that's existing code, see the next line of the diff - i've just assigned it to the variable to avoid writing c.screen..... twice

Comment (actionless) [reply lib/awful/layout/suit/tile.lua:54]: answering your question - having two tags (with different params) selected in awesome i think not documented behavior, but i think everywhere it defaults to params of the first (by idx) of selected tags - although this PR is not the best place to discuss that behavior

**Review by Aire-One — APPROVED** [review]

**Review by Elv13 — APPROVED** [review]
